#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# We have to chown the zeppelin directories to make it usable for
# the default user. Unfortunately the user does not exists when DIB
# is creating the image and we need to execute this code the
# first time the VM boots.

firstboot_script_name="/opt/spark/firstboot.sh"

if [ "$DISTRO_NAME" = "fedora" ]; then
    cat >> /etc/rc.d/rc.local <<EOF
#!/bin/sh
if [ -f $firstboot_script_name ]; then
    sh $firstboot_script_name
fi
exit 0
EOF

    user_group_names="fedora:fedora"
fi

if [ "$DISTRO_NAME" = "ubuntu" ]; then
    sed -i -e "s,^exit 0$,[ -f $firstboot_script_name ] \&\& sh $firstboot_script_name; exit 0," /etc/rc.local

    user_group_names="ubuntu:ubuntu"
fi

cat >> $firstboot_script_name <<EOF
#!/bin/sh
chown -R $user_group_names /opt/incubator-zeppelin
rm $firstboot_script_name
EOF